# Generated by Django 5.2.7 on 2026-05-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_category_type_product_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
