# Generated by Django 5.2.7 on 2026-06-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_userprofile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bmi_category',
            field=models.CharField(blank=True, default='Normal', max_length=50),
        ),
    ]
